/* Generated by Cython 0.28 */

#ifndef __PYX_HAVE__project__rar__ks_test
#define __PYX_HAVE__project__rar__ks_test


#ifndef __PYX_HAVE_API__project__rar__ks_test

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C double _calculate_max_dist(__Pyx_memviewslice, __Pyx_memviewslice);

#endif /* !__PYX_HAVE_API__project__rar__ks_test */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initks_test(void);
#else
PyMODINIT_FUNC PyInit_ks_test(void);
#endif

#endif /* !__PYX_HAVE__project__rar__ks_test */
